n=int(input("Введите номер месяца :"))
def quarter_of_year(n):
    if n==1: print("I Квартал")
    elif n==2: print("I Квартал")
    elif n==3: print("I Квартал")
    elif n==4: print("II Квартал")
    elif n==5: print("II Квартал")
    elif n==6: print("II Квартал")
    elif n==7: print("III Квартал")
    elif n==8: print("III Квартал")
    elif n==9: print("III Квартал")
    elif n==10:print("IV Квартал")
    elif n==11:print("IV Квартал")
    elif n==12:print("IV Квартал")
    else:print("95 КВАРТАЛ")
quarter_of_year(n)